SR = 16000
FRAME_MS = 30
FRAME_SAMPLES = SR * FRAME_MS // 1000

VAD_AGGRESSIVENESS = 2
SILENCE_MS = 800
PARTIAL_INTERVAL_S = 1.5
MIN_SPEECH_MS = 300
MAX_UTTERANCE_S = 30

MODEL = "base"
DEVICE = "cpu"
COMPUTE_TYPE = "int8"

LANGUAGE = "en"
VAD_FILTER = False
WITHOUT_TIMESTAMPS = True
